return {
	"xiyaowong/transparent.nvim",
	event = "VeryLazy",
	opts = {
		groups = {
			"Normal",
			"NormalNC",
			"Comment",
			"Constant",
			"Special",
			"Identifier",
			"Statement",
			"PreProc",
			"Type",
			"Underlined",
			"Todo",
			"String",
			"Function",
			"Conditional",
			"Repeat",
			"Operator",
			"Structure",
			"LineNr",
			"NonText",
			"SignColumn",
			"CursorLine",
			"CursorLineNr",
			"StatusLine",
			"StatusLineNC",
			"EndOfBuffer",
		},
		extra_groups = {
			"Pmenu",
			"PmenuSbar",
			"FloatBorder",
			"NormalFloat",
		},
		exclude_groups = {},
	},
}
