local M = {
	"xiyaowong/transparent.nvim",
}

function M.config()
	require("transparent").setup({
		groups = { -- table: default groups
			-- ... your other default groups are fine ...
			"Normal",
			"NormalNC",
			"Comment",
			"Constant",
			"Special",
			"Identifier",
			"Statement",
			"PreProc",
			"Type",
			"Underlined",
			"Todo",
			"String",
			"Function",
			"Conditional",
			"Repeat",
			"Operator",
			"Structure",
			"LineNr",
			"NonText",
			"SignColumn",
			"CursorLine",
			"CursorLineNr",
			"StatusLine",
			"StatusLineNC",
			"EndOfBuffer",
		},
		extra_groups = {
			-- Add these groups for the popup menu! 👇
			"Pmenu",
			"PmenuSbar",
			"FloatBorder",

			-- Your existing extra groups
			"NormalFloat",
			"NvimTreeNormal",
			"Fidget",
			"NeoTreeCursorLine",
			"NeoTreeDimText",
			"NeoTreeDirectoryIcon",
			"NeoTreeDirectoryName",
			"NeoTreeDotfile",
			"NeoTreeFileIcon",
			"NeoTreeFileName",
			"NeoTreeFileNameOpene",
			"NeoTreeFilterTerm",
			"NeoTreeFloatBorder",
			"NeoTreeFloatTitle",
			"NeoTreeTitleBar",
			"NeoTreeGitAdded",
			"NeoTreeGitConflict",
			"NeoTreeGitDeleted",
			"NeoTreeGitIgnored",
			"NeoTreeGitModified",
			"NeoTreeGitUnstaged",
			"NeoTreeGitUntracke",
			"NeoTreeGitStaged",
			"NeoTreeHiddenByName",
			"NeoTreeIndentMarker",
			"NeoTreeExpander",
			"NeoTreeNormal",
			"NeoTreeNormalNC",
			"NeoTreeSignColumn",
			"NeoTreeStatusLine",
			"NeoTreeStatusLineNC",
			"NeoTreeVertSplit",
			"NeoTreeWinSeparator",
			"NeoTreeEndOfBuffer",
			"NeoTreeRootName",
			"NeoTreeSymbolicLinkTarget",
			"NeoTreeTitleBar",
			"NeoTreeWindowsHidden",
		},
		exclude_groups = {}, -- table: groups you don't want to clear
	})
end

return M
